apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: healthcat-rs-argocd-apps-reader
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: healthcat-rs-argocd-apps-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: healthcat-rs-argocd-apps-reader
subjects:
- kind: ServiceAccount
  name: healthcat-rs
  namespace: app-health-5g
