apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: healthcat-rs-openshift-routes-reader
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
 
--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: healthcat-rs-openshift-routes-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: healthcat-rs-openshift-routes-reader
subjects:
- kind: ServiceAccount
  name: healthcat-rs
  namespace: app-health-5g
