apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: casa-platform-ci-read
  namespace: dimitar
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  verbs:
  - get
  - list
  - watch
