apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: vzw-tekton-server-catalog
  name: tekton-http-server-e2e-test
  namespace: dimitar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-http-server-e2e-test
subjects:
- kind: ServiceAccount
  name: tekton-http-server-e2e-test
