apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: Deployment
    tekton.dev/platforms: linux/amd64,linux/s390x,linux/ppc64le,linux/arm64
    tekton.dev/tags: helm
  labels:
    app.kubernetes.io/instance: tekton-catalog
    app.kubernetes.io/version: 0.1.0
  name: helm-uninstall
  namespace: dimitar
spec:
  description: Uninstall a Helm Release
  params:
  - default: helm-release
    description: Helm Release name
    name: release_name
    type: string
  - default: ""
    description: Helm release namespace
    name: release_namespace
    type: string
  - default: docker.artifactory.casa-systems.com/lachlanevenson/k8s-helm:v3.10.2
    description: Helm image to use
    name: helm_image
    type: string
  - default: ""
    description: Extra parameters passed for the helm uuninstall command
    name: uninstall_extra_params
    type: string
  steps:
  - computeResources:
      limits:
        cpu: "2"
        memory: 750Mi
      requests:
        cpu: 250m
        memory: 100Mi
    image: $(params.helm_image)
    name: uninstall
    script: |-
      echo Currently installed Helm Releases
      helm list --namespace "$(params.release_namespace)"

      echo Uninstalling Helm Release...
      helm uninstall --wait --namespace "$(params.release_namespace)" "$(params.release_name)" --debug $(params.uninstall_extra_params)
