apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcat-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: healthcat-rs
  strategy:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: healthcat-rs
    spec:
      containers:
      - name: healthcat-rs
        image: registry.gitlab.casa-systems.com/dimitar.georgievski/healthcat-rs:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: APP_ENVIRONMENT
          value: dev
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext: {}
        volumeMounts:
        - mountPath: /app/etc/
          name: config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccount: healthcat-rs
      serviceAccountName: healthcat-rs
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: healthcat-rs-config
