apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: healthcat-rs-tekton-reader
rules:
- apiGroups: 
    - tekton.dev
  resources:
    - tasks
    - taskruns
    - pipelines
    - pipelineruns
    - pipelineresources
    - conditions
  verbs: 
    - get
    - list
    - watch
- apiGroups: 
    - ""
    - events.k8s.io
  resources: 
    - pods
    - events
  verbs: 
    - get
    - list
    - watch
- apiGroups: 
    - metrics.k8s.io
  resources:
    - pods
    - nodes
  verbs:
    - get
    - list
    - watch
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: healthcat-rs-tekton-reader
subjects:
- kind: ServiceAccount
  name: healthcat-rs
  namespace: app-health-5g
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: healthcat-rs-tekton-reader
  apiGroup: rbac.authorization.k8s.io
