apiVersion: v1
kind: Service
metadata:
  name: healthcat-rs
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: healthcat-rs
  sessionAffinity: None
  type: ClusterIP
