application:
  port: 8000
  host: 0.0.0.0
kube:
  use_tls: false
  # events is always element of resources. It's added if missing.
  resources:
    - deployments
  # [] for cluster scope ie all namespaces
  namespaces: []

  # TODO watch resources per diff namespaces
  watch:
    - resources: []
      namespaces: []

  