application:
  port: 8000
  host: 0.0.0.0
kube:
  use_tls: false
  resources:
    - applications
    - routes
    - ingresses
  # [] for cluster scope ie all namespaces
  namespaces:
    # - tenant-upf
    - openshift-gitops

  # resources:
  #   - name: events
  #     namespaces: 
  #       - app-health-5g
  #     labels: []
  #     fieldsSelectors:
  #       - "type!=Mormal"
  